name: Shopee Robot CI + Discord

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  robot-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Setup Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Upgrade pip & Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install webdrivermanager

    - name: Remove old chromedriver if exists
      run: |
        sudo rm -f /usr/local/bin/chromedriver || true

    - name: Setup ChromeDriver
      run: |
        CHROME_VERSION=$(google-chrome --version | grep -oP '\d+')
        echo "Detected Chrome major version: $CHROME_VERSION"

        # Fungsi cek apakah URL chromedriver versi itu valid
        check_version() {
          curl --silent --head --fail https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$1
        }

        # Coba versi Chrome detected, fallback ke versi sebelumnya jika tidak ada
        VERSION_TO_CHECK=$CHROME_VERSION
        while ! check_version $VERSION_TO_CHECK && [ $VERSION_TO_CHECK -gt 80 ]; do
          echo "Version $VERSION_TO_CHECK not found, fallback ke versi sebelumnya"
          VERSION_TO_CHECK=$((VERSION_TO_CHECK-1))
        done

        CHROME_DRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$VERSION_TO_CHECK)
        echo "Downloading chromedriver version $CHROME_DRIVER_VERSION"

        wget -N https://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/chromedriver
        sudo chmod +x /usr/local/bin/chromedriver



    - name: Check Chrome & Chromedriver versions
      run: |
        google-chrome --version
        chromedriver --version

    - name: Run Robot Tests (Headless Chrome with needed options)
      run: |
        robot --variable BROWSER:headlesschrome \
              --variable CHROME_OPTIONS:"--headless=new --no-sandbox --disable-dev-shm-usage --disable-gpu" \
              --outputdir results tests/

    # - name: Upload Robot Report
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: robot-report
    #     path: results/

    - name: Notify Discord
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      run: |
        curl -H "Content-Type: application/json" \
             -X POST \
             -d "{\"content\":\":white_check_mark: Test Shopee selesai!\\n🔗 [Lihat hasil GitHub Actions](${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID})\"}" \
             $DISCORD_WEBHOOK